fname = input("Enter First Name: ")
lname = input("Enter Last Name: ")
mname = input("Enter Middle Name: ")
birdthday = input("Enter Birthday: ")
gender = input("Enter Gender: ")
address = input("Enter Address: ")
course = input("Enter Course: ")
yearlevel = input("Enter Year Level: ")

print ("First Name: ", fname)
print ("Last Name: ", lname)
print ("Middle Name: ", mname)
print ("Birthday: ", birdthday)
print ("Gender: ", gender)
print ("Address: ", address)
print ("Course: ", course)
print ("Year Level: ", yearlevel)